from dotenv import load_dotenv
from deepagents import create_deep_agent
from langchain_anthropic import ChatAnthropic
from langchain_core.tools import tool

# Load ANTHROPIC_API_KEY from the .env file
load_dotenv()

# TOOL: Destination Information Lookup
@tool
def get_destination_info(destination_name: str) -> str:
    """
    Get reference travel information about one tropical destination.

    Args:
        destination_name: The full destination name,
        for example Aruba, Jamaica, or Bahamas.
    """

# Mock destination knowledge for the prototype
    destinations = {
        "bahamas": "The Bahamas is known for beaches, warm weather, and island activities.",
        "jamaica": "Jamaica is known for beaches, reggae culture, waterfalls, and local cuisine.",
        "aruba": "Aruba is known for dry sunny weather, beaches, and water sports."
    }

    return destinations.get(
        destination_name.lower(),
        "No destination information is available for that location."
    )

# TOOL: Destination Search by Preferences
@tool
def search_destinations(preferences: list[str]) -> str:
    """
    Find tropical destinations that match a travel preferences.

    Args:
        preferences: A list of travel preferences, for example
        ["beaches", "water sports"] or
        ["waterfalls", "local cuisine"].
    """

    destinations = {
        "Bahamas": {
            "features": [
                "beaches",
                "warm weather",
                "island activities"
            ]
        },
        "Jamaica": {
            "features": [
                "beaches",
                "reggae culture",
                "waterfalls",
                "local cuisine"
            ]
        },
        "Aruba": {
            "features": [
                "dry sunny weather",
                "beaches",
                "water sports"
            ]
        },
    }

    matches = []

    # Check whether the user's preferences appears
    # in the destination information.
    for destination, data in destinations.items():
        features = data["features"]
        matched_preferences = []

        for preference in preferences:
            for feature in features:
                if preference.lower() in feature.lower():
                    matched_preferences.append(preference)
                    break

        if matched_preferences:
            matches.append(
                f"Destination: {destination}\n"
                f"Features: {', '.join(features)}\n"
                f"Matched Preferences: {', '.join(matched_preferences)}"
            )

    if matches:
        return "\n".join(matches)

    return "No matching destinations were found."

# LLM MODEL
model = ChatAnthropic(
    model="claude-haiku-4-5",
    temperature=0
)

# DESTINATION EXPERT AGENT
agent = create_deep_agent(
    model=model,
    tools=[
    get_destination_info,
    search_destinations
    ],
    system_prompt="""
    You are a Destination Expert Agent in a multi-agent travel planning system.

    Your responsibilities are:
    1. Provide information about a specific tropical destination.
    2. Help identify destinations that match a user's travel preferences.
    
    Available tools:
    1. get_destination_info: Use this when the user asks about a specific destination.
    2. search_destinations: Use this when the user describes one or more travel preferences and wants help choosing a destination.

    Return your final response in this format:
    Recommended Destination: <destination name>
    Reason: <short explanation based on the tool result>
    Matched Preferences: <preferences that match>

    IMPORTANT RULES:
    Do not add facts from your own knowledge.
    Do not infer activities, weather details, geography, or other information that is not explicitly present in the tool output.
    Keep the response concise because this result may later be passed to an Orchestrator Agent.
    """
)

# DESTINATION AGENT RUNNER
def run_destination_agent(user_query: str) -> str:
    """
    Run the Destination Expert Agent.

    Args:
        user_query: A destination-related request from the user
        or from the Orchestrator Agent.

    Returns:
        The final text response generated by the Destination Agent.
    """

    result = agent.invoke(
        {
            "messages": [
                {
                    "role": "user",
                    "content": user_query
                }
            ]
        }
    )

    # Return only the final Destination Agent response.
    # This makes the function easy for an Orchestrator to use.
    return result["messages"][-1].content

# LOCAL TEST
if __name__ == "__main__":

    test_query = (
        "I want a tropical destination with beaches and water sports. "
        "Where should I go?"
    )

    response = run_destination_agent(test_query)

    print("\nDESTINATION AGENT RESPONSE:\n")
    print(response)

    